/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contentAccessManagerSol from "./ContentAccessManager.sol";
export type { contentAccessManagerSol };
