/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace ITeleporterMessenger {
  export type TeleporterFeeInfoStruct = {
    feeTokenAddress: AddressLike;
    amount: BigNumberish;
  };

  export type TeleporterFeeInfoStructOutput = [
    feeTokenAddress: string,
    amount: bigint
  ] & { feeTokenAddress: string; amount: bigint };

  export type TeleporterMessageInputStruct = {
    destinationBlockchainID: BytesLike;
    destinationAddress: AddressLike;
    feeInfo: ITeleporterMessenger.TeleporterFeeInfoStruct;
    requiredGasLimit: BigNumberish;
    allowedRelayerAddresses: AddressLike[];
    message: BytesLike;
  };

  export type TeleporterMessageInputStructOutput = [
    destinationBlockchainID: string,
    destinationAddress: string,
    feeInfo: ITeleporterMessenger.TeleporterFeeInfoStructOutput,
    requiredGasLimit: bigint,
    allowedRelayerAddresses: string[],
    message: string
  ] & {
    destinationBlockchainID: string;
    destinationAddress: string;
    feeInfo: ITeleporterMessenger.TeleporterFeeInfoStructOutput;
    requiredGasLimit: bigint;
    allowedRelayerAddresses: string[];
    message: string;
  };
}

export interface ITeleporterMessengerInterface extends Interface {
  getFunction(nameOrSignature: "sendCrossChainMessage"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "sendCrossChainMessage",
    values: [ITeleporterMessenger.TeleporterMessageInputStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "sendCrossChainMessage",
    data: BytesLike
  ): Result;
}

export interface ITeleporterMessenger extends BaseContract {
  connect(runner?: ContractRunner | null): ITeleporterMessenger;
  waitForDeployment(): Promise<this>;

  interface: ITeleporterMessengerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  sendCrossChainMessage: TypedContractMethod<
    [messageInput: ITeleporterMessenger.TeleporterMessageInputStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "sendCrossChainMessage"
  ): TypedContractMethod<
    [messageInput: ITeleporterMessenger.TeleporterMessageInputStruct],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
