/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace PaymentRegistry {
  export type PaymentStruct = {
    buyer: AddressLike;
    contentId: BytesLike;
    amount: BigNumberish;
    paymentTxHash: BytesLike;
    timestamp: BigNumberish;
    settled: boolean;
  };

  export type PaymentStructOutput = [
    buyer: string,
    contentId: string,
    amount: bigint,
    paymentTxHash: string,
    timestamp: bigint,
    settled: boolean
  ] & {
    buyer: string;
    contentId: string;
    amount: bigint;
    paymentTxHash: string;
    timestamp: bigint;
    settled: boolean;
  };
}

export interface PaymentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contentAccessManagerOnEcho"
      | "echoChainID"
      | "getPayment"
      | "isPaymentSettled"
      | "owner"
      | "payments"
      | "renounceOwnership"
      | "settlePayment"
      | "teleporterMessenger"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CrossChainMessageSent"
      | "OwnershipTransferred"
      | "PaymentSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "contentAccessManagerOnEcho",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "echoChainID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPaymentSettled",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payments",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settlePayment",
    values: [AddressLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "teleporterMessenger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "contentAccessManagerOnEcho",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "echoChainID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPaymentSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "teleporterMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CrossChainMessageSentEvent {
  export type InputTuple = [
    buyer: AddressLike,
    contentId: BytesLike,
    teleporterMessageID: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    contentId: string,
    teleporterMessageID: bigint
  ];
  export interface OutputObject {
    buyer: string;
    contentId: string;
    teleporterMessageID: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSettledEvent {
  export type InputTuple = [
    buyer: AddressLike,
    contentId: BytesLike,
    amount: BigNumberish,
    paymentTxHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    contentId: string,
    amount: bigint,
    paymentTxHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    buyer: string;
    contentId: string;
    amount: bigint;
    paymentTxHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentRegistry;
  waitForDeployment(): Promise<this>;

  interface: PaymentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contentAccessManagerOnEcho: TypedContractMethod<[], [string], "view">;

  echoChainID: TypedContractMethod<[], [string], "view">;

  getPayment: TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [PaymentRegistry.PaymentStructOutput],
    "view"
  >;

  isPaymentSettled: TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payments: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [
      [string, string, bigint, string, bigint, boolean] & {
        buyer: string;
        contentId: string;
        amount: bigint;
        paymentTxHash: string;
        timestamp: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settlePayment: TypedContractMethod<
    [
      buyer: AddressLike,
      contentId: BytesLike,
      amount: BigNumberish,
      paymentTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  teleporterMessenger: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contentAccessManagerOnEcho"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "echoChainID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [PaymentRegistry.PaymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPaymentSettled"
  ): TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [
      [string, string, bigint, string, bigint, boolean] & {
        buyer: string;
        contentId: string;
        amount: bigint;
        paymentTxHash: string;
        timestamp: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlePayment"
  ): TypedContractMethod<
    [
      buyer: AddressLike,
      contentId: BytesLike,
      amount: BigNumberish,
      paymentTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "teleporterMessenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CrossChainMessageSent"
  ): TypedContractEvent<
    CrossChainMessageSentEvent.InputTuple,
    CrossChainMessageSentEvent.OutputTuple,
    CrossChainMessageSentEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSettled"
  ): TypedContractEvent<
    PaymentSettledEvent.InputTuple,
    PaymentSettledEvent.OutputTuple,
    PaymentSettledEvent.OutputObject
  >;

  filters: {
    "CrossChainMessageSent(address,bytes32,uint256)": TypedContractEvent<
      CrossChainMessageSentEvent.InputTuple,
      CrossChainMessageSentEvent.OutputTuple,
      CrossChainMessageSentEvent.OutputObject
    >;
    CrossChainMessageSent: TypedContractEvent<
      CrossChainMessageSentEvent.InputTuple,
      CrossChainMessageSentEvent.OutputTuple,
      CrossChainMessageSentEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentSettled(address,bytes32,uint256,bytes32,uint256)": TypedContractEvent<
      PaymentSettledEvent.InputTuple,
      PaymentSettledEvent.OutputTuple,
      PaymentSettledEvent.OutputObject
    >;
    PaymentSettled: TypedContractEvent<
      PaymentSettledEvent.InputTuple,
      PaymentSettledEvent.OutputTuple,
      PaymentSettledEvent.OutputObject
    >;
  };
}
