/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as paymentRegistrySol from "./PaymentRegistry.sol";
export type { paymentRegistrySol };
export type { ERC3009PaymentToken } from "./ERC3009PaymentToken";
