[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

# デフォルトのRPC URL
# デプロイ時に --rpc-url オプションで上書きされます
eth_rpc_url = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
