/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITeleporterReceiver,
  ITeleporterReceiverInterface,
} from "../../../../src/Echo/ContentAccessManager.sol/ITeleporterReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "originChainID",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "originSenderAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "receiveTeleporterMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITeleporterReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): ITeleporterReceiverInterface {
    return new Interface(_abi) as ITeleporterReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITeleporterReceiver {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ITeleporterReceiver;
  }
}
