/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITeleporterMessenger,
  ITeleporterMessengerInterface,
} from "../../../../src/Dispatch/PaymentRegistry.sol/ITeleporterMessenger";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "destinationBlockchainID",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "destinationAddress",
            type: "address",
          },
          {
            components: [
              {
                internalType: "address",
                name: "feeTokenAddress",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            internalType: "struct ITeleporterMessenger.TeleporterFeeInfo",
            name: "feeInfo",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "requiredGasLimit",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "allowedRelayerAddresses",
            type: "address[]",
          },
          {
            internalType: "bytes",
            name: "message",
            type: "bytes",
          },
        ],
        internalType: "struct ITeleporterMessenger.TeleporterMessageInput",
        name: "messageInput",
        type: "tuple",
      },
    ],
    name: "sendCrossChainMessage",
    outputs: [
      {
        internalType: "uint256",
        name: "messageID",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITeleporterMessenger__factory {
  static readonly abi = _abi;
  static createInterface(): ITeleporterMessengerInterface {
    return new Interface(_abi) as ITeleporterMessengerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITeleporterMessenger {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ITeleporterMessenger;
  }
}
