/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace ContentAccessManager {
  export type AccessGrantStruct = {
    buyer: AddressLike;
    contentId: BytesLike;
    amount: BigNumberish;
    paymentTxHash: BytesLike;
    grantedAt: BigNumberish;
  };

  export type AccessGrantStructOutput = [
    buyer: string,
    contentId: string,
    amount: bigint,
    paymentTxHash: string,
    grantedAt: bigint
  ] & {
    buyer: string;
    contentId: string;
    amount: bigint;
    paymentTxHash: string;
    grantedAt: bigint;
  };
}

export interface ContentAccessManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "access"
      | "accessGrants"
      | "dispatchChainID"
      | "getAccessGrant"
      | "hasAccess"
      | "manualGrantAccess"
      | "owner"
      | "paymentRegistryOnDispatch"
      | "receiveTeleporterMessage"
      | "renounceOwnership"
      | "revokeAccess"
      | "teleporterMessenger"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AccessGranted" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "access",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "accessGrants",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dispatchChainID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessGrant",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manualGrantAccess",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentRegistryOnDispatch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveTeleporterMessage",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "teleporterMessenger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "access", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accessGrants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dispatchChainID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessGrant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manualGrantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentRegistryOnDispatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveTeleporterMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "teleporterMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    contentId: BytesLike,
    amount: BigNumberish,
    paymentTxHash: BytesLike,
    grantedAt: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    contentId: string,
    amount: bigint,
    paymentTxHash: string,
    grantedAt: bigint
  ];
  export interface OutputObject {
    buyer: string;
    contentId: string;
    amount: bigint;
    paymentTxHash: string;
    grantedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContentAccessManager extends BaseContract {
  connect(runner?: ContractRunner | null): ContentAccessManager;
  waitForDeployment(): Promise<this>;

  interface: ContentAccessManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  access: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  accessGrants: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [
      [string, string, bigint, string, bigint] & {
        buyer: string;
        contentId: string;
        amount: bigint;
        paymentTxHash: string;
        grantedAt: bigint;
      }
    ],
    "view"
  >;

  dispatchChainID: TypedContractMethod<[], [string], "view">;

  getAccessGrant: TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [ContentAccessManager.AccessGrantStructOutput],
    "view"
  >;

  hasAccess: TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [boolean],
    "view"
  >;

  manualGrantAccess: TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paymentRegistryOnDispatch: TypedContractMethod<[], [string], "view">;

  receiveTeleporterMessage: TypedContractMethod<
    [
      originChainID: BytesLike,
      originSenderAddress: AddressLike,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeAccess: TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [void],
    "nonpayable"
  >;

  teleporterMessenger: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "access"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "accessGrants"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [
      [string, string, bigint, string, bigint] & {
        buyer: string;
        contentId: string;
        amount: bigint;
        paymentTxHash: string;
        grantedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "dispatchChainID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAccessGrant"
  ): TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [ContentAccessManager.AccessGrantStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "manualGrantAccess"
  ): TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentRegistryOnDispatch"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiveTeleporterMessage"
  ): TypedContractMethod<
    [
      originChainID: BytesLike,
      originSenderAddress: AddressLike,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [buyer: AddressLike, contentId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "teleporterMessenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AccessGranted(address,bytes32,uint256,bytes32,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
