/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ContentAccessManager } from "./ContentAccessManager";
export type { ITeleporterReceiver } from "./ITeleporterReceiver";
